/*
 * TreatmentGUI.java
 *
 * Created on 10 sierpień 2008, 16:08
 */
package medicalcryptoappclient.gui;

import beans.statefull.DoctorRemote;
import entities.medical.dto.TreatmentDTO;
import entities.medical.dto.VisitDTO;
import exceptions.CryptographyException;
import exceptions.DatabaseException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author  Piotrek
 */
public class TreatmentGUI extends javax.swing.JFrame {

    /** Creates new form TreatmentGUI */
    public TreatmentGUI(JFrame parent, DoctorRemote doctorBean, VisitDTO visitDTO) {
        initComponents();
        this.parent = parent;
        this.doctorBean = doctorBean;
        this.visitDTO = visitDTO;
    }

    public TreatmentGUI(JFrame parent, DoctorRemote doctorBean, TreatmentDTO treatmentToEditDTO) {
        initComponents();
        this.parent = parent;
        this.doctorBean = doctorBean;
        this.treatmentToEditDTO = treatmentToEditDTO;
        medicinejTextField.setText(treatmentToEditDTO.getMedicine());
        dosagejTextArea.setText(treatmentToEditDTO.getDosage());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        medicinejTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        dosagejTextArea = new javax.swing.JTextArea();
        OKjButton = new javax.swing.JButton();
        canceljButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Leczenie");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Leczenie:"));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Lek:");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Dawkowanie:");

        dosagejTextArea.setColumns(20);
        dosagejTextArea.setRows(5);
        jScrollPane1.setViewportView(dosagejTextArea);

        OKjButton.setText("OK");
        OKjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKjButtonActionPerformed(evt);
            }
        });

        canceljButton.setText("Anuluj");
        canceljButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canceljButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                            .addComponent(medicinejTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(canceljButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(OKjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(medicinejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OKjButton)
                    .addComponent(canceljButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void canceljButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canceljButtonActionPerformed
    this.setVisible(false);
    parent.setEnabled(true);
    parent.toFront();
    this.dispose();
}//GEN-LAST:event_canceljButtonActionPerformed

private void OKjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKjButtonActionPerformed
    try {
        String medicine = medicinejTextField.getText();
        String dosage = dosagejTextArea.getText();
        if (medicine.length() > 0 && dosage.length() > 0) {
            boolean result;
            if (visitDTO == null) {
                treatmentToEditDTO.setMedicine(medicine);
                treatmentToEditDTO.setDosage(dosage);
                result = doctorBean.editTreatment(treatmentToEditDTO);
            } else {
                TreatmentDTO treatmentDTO = new TreatmentDTO(medicine, dosage);
                result = doctorBean.createTreatment(treatmentDTO, visitDTO.getIdVisit());
            }
            if (result) {
                GUIDoctor parentGUI = (GUIDoctor) parent;
                this.setVisible(false);
                parent.setEnabled(true);
                parent.toFront();
                parentGUI.callTreatmentDoctorItemActionPerformed(evt);
                this.dispose();
            }
        } else {
            JOptionPane.showMessageDialog(this,
                    "Wystąpił błąd przy zapisie danych\nSkontaktuj się z administratorem",
                    "Błąd",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
    } catch (CryptographyException ex) {
        JOptionPane.showMessageDialog(this,
                "Wystąpił błąd przy przetwarzaniu danych\nSkontaktuj się z administratorem",
                "Błąd",
                JOptionPane.ERROR_MESSAGE);
    } catch (DatabaseException ex) {
        JOptionPane.showMessageDialog(this,
                "Wystąpił błąd przy zapisie danych\nSkontaktuj się z administratorem",
                "Błąd",
                JOptionPane.ERROR_MESSAGE);
    }
}//GEN-LAST:event_OKjButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OKjButton;
    private javax.swing.JButton canceljButton;
    private javax.swing.JTextArea dosagejTextArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField medicinejTextField;
    // End of variables declaration//GEN-END:variables
    VisitDTO visitDTO = null;
    TreatmentDTO treatmentToEditDTO = null;
    DoctorRemote doctorBean = null;
    JFrame parent = null;
}
